---
- name: Configure Papertrail
  template:
    src: log_files.yml.j2
    dest: "{{ papertrail_config_file_path }}/log_files.yml"
    owner: "{{ papertrail_managed_conf_file_owner }}"
    group: "{{ papertrail_managed_conf_file_group }}"
    mode: "{{ papertrail_managed_conf_file_mode | string }}"
    backup: "{{ papertrail_managed_conf_file_backup }}"
    force: true
  notify: restart papertrail
  when: papertrail_managed_conf_file and papertrail_destination_host | length

- name: Configure Papertrail service
  service:
    name: "{{ papertrail_service_name }}"
    state: "{{ papertrail_service_state }}"
