---
- name: Install Papertrail (RedHat)
  yum:
    name: "{{ papertrail_download_url }}/{{ papertrail_package_name }}"
    state: present
    validate_certs: "{{ papertrail_check_download_certs }}"
  when: ansible_os_family == "RedHat"

- name: Install Papertrail (Debian)
  apt:
    deb: "{{ papertrail_download_url }}/{{ papertrail_package_name }}"
    update_cache: true
    force: "{{ False if papertrail_check_download_certs | bool else papertrail_check_download_certs }}"
  when: ansible_os_family == "Debian"
